# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4a8026a0a94a5eb9878cc7cf2d5fccc6e37a529af549eb10ca81c326e79365ac5bdf28cb4637dea2316f261f6c76e50d208099309f67a7ca0f2a4bf7a24896

test:
  secret_key_base: ce203eeb9717394ead433edf9a23d451c27a74e5ad657ecaef89e4a5c0b095dcf169f4059a58069cab056c8ad9b201637f4fcce76e45a4090a0d4f7f3633acc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
